### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MultiProposal'

### ISSUE THREAD

**Issue by lemontree561** [msracver/Deep-Feature-Flow#11]
Hi, @daijifeng001 @Orpine,I use python interactive console to print mxnet.__path__,
it shows  '/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet'

so I don't konw if it is right. I hope you can slove the AttributeError: 'module' object has no attribute 'MultiProposal'.

Thank you!

**Comment by Orpine** [comment]
Please ensure that you installed the recompiled mxnet into this path.

**Comment by lemontree561** [comment]
@Orpine,I don't know what you mean,I install the mxnet in the $HOME/mxnet path ,I just follow the 
    below  ways:
   git clone https://github.com/dmlc/mxnet.git ~/mxnet --recursive
    cd ~/mxnet
    cp make/config.mk ,and then change something in the config.mk
    make -j8
    cd python 
    python setup.py install
    cp operator/-cxx  $HOME/mxnet／src/operator/contrib
    make clean 
    make -j8

**Comment by Orpine** [comment]
then you need to go to 'python' folder and run 'python setup.py install', maybe you need sudo

**Comment by lemontree561** [comment]
Hi @Orpine,I went to the ~/mxnet/python and then to run 'sudo python setup.py install' ,
cp operator/-cxx $HOME/mxnet／src/operator/contrib
make clean     make -j8 
But I still face the problem of 'AttributeError: 'module' object has no attribute 'MultiProposal' when I run 'python ./rfcn/demo.py ', I don't konw how to correct it.I don't konw where is wrong.

**Comment by Orpine** [comment]
Please follow these steps: 1. copy source code 2. compile 3. install mxnet

**Comment by lemontree561** [comment]
Hi @Orpine,the source code is Deep-Feature-Flow.git? I just follow the README.md 1.Requirement Software,so I install mxnet.2.Clone the Deep-Feature-Flow.git.3.Copy operators,Recompile the mxnet.
The below is my all steps:
install cuda,cudnn
git clone https://github.com/dmlc/mxnet.git ~/mxnet --recursive
cd ~/mxnet
cp make/config.mk ,and then change something in the config.mk
make -j8
cd  ~/mxnet/python
sudo python setup.py install
cp operator/-cxx $HOME/mxnet／src/operator/contrib
cd ~/mxnet
make clean
make -j8
cd Deep-Feature-Flow and then run python ./rfcn/demo.py
So where is wrong ,lead to the AttributeError: 'module' object has no attribute 'MultiProposal'?

**Comment by RyanCV** [comment]
@lemontree561 I have the same problem as u, did u solve this problem? Thanks.

**Comment by RyanCV** [comment]
@lemontree561 I just solved this problem. Once u recompile the mxnet, u need to do the following step: `cd python; python setup.py install`. I got this from the website: `https://no2147483647.wordpress.com/2015/12/07/deep-learning-for-hackers-with-mxnet-1/`.
