### ISSUE TITLE
how could i recompile mxnet with new operator_cxx files?

### ISSUE THREAD

**Issue by seongkyun** [msracver/Deep-Feature-Flow#12]
with

Ubuntu 16.04LTS, geforce gtx 1060(6gb), cuda 8.0 cudnn 5.1

and Anaconda 2.

i installed mxnet with 

`$ pip install mxnet-cu80`

and other requirements.

but there is any path like

`(my mxnet source)src/operator/contrib`

only has(used print mxnet.__path__ in python)

`/home/(name)/anaconda2/lib/python2.7/site-packages/mxnet`

how could i recompile mxnet with new operator_cxx files????

plz help me :)

**Comment by Orpine** [comment]
Please do not install MXNet by pip but compile it by your own.
