### ISSUE TITLE
Demo Error: no attribute 'IMREAD_IGNORE_ORIENTATION'

### ISSUE THREAD

**Issue by TerryLovesLife** [msracver/Deep-Feature-Flow#13]
Hi, 

 'output_path': './output/rfcn/imagenet_vid',
 'symbol': ''}
Traceback (most recent call last):
  File "./rfcn/demo.py", line 142, in <module>
    main()
  File "./rfcn/demo.py", line 73, in main
    im = cv2.imread(im_name, cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
AttributeError: 'module' object has no attribute 'IMREAD_IGNORE_ORIENTATION'

I do have copies the four files under operator_cxx to (MXNET_FOLDER)/src/operator/contrib

rfcn/operator_cxx
                           |-------multi_proposal.cc  multi_proposal-inl.h  multi_proposal.cu  psroi_pooling.cc psroi_pooling-inl.h psroi_pooling.cc psroi_pooling.cu

mxnet/src/operator/contrib
                                      |-------multi_proposal.cc  multi_proposal-inl.h  multi_proposal.cu  psroi_pooling.cc psroi_pooling-inl.h psroi_pooling.cc psroi_pooling.cu  

and recompile mxnet:     make -j $(nproc) USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1

and install in (MXNET_FOLDER)/python:       sudo python setup.py install. 

The error shows when I run the demo. I have tried the same on another server, the same error shows. How to solve this problem?  Thank you.

**Comment by Orpine** [comment]
Please read our readme, this repo requires opencv-python==3.2.0.6
