### ISSUE TITLE
Training models using Deep Feature Flow with R-FCN

### ISSUE THREAD

**Issue by TerryLovesLife** [msracver/Deep-Feature-Flow#14]
Hi,

When I train and test Deep Feature Flow with R-FCN, using the following command:
python experiments/dff_rfcn/dff_rfcn_end2end_train_test.py --cfg experiments/dff_rfcn/cfgs/resnet_v1_101_flownet_imagenet_vid_rfcn_end2end_ohem.yaml

AssertionError: Path does not exist: ./data/ILSVRC2015/ImageSets/DET_train_30classes.txt

Is it only 30 classes information  for VID in DET_train_30classes.txt, what is the calss data format inside txt file? Or where can I download the DET_train_30calsses.txt ?? 

Thank you !!!

**Comment by Orpine** [comment]
DET_train_30classes.txt is a part of our repo, it is in data/ILSVRC2015/ImageSets

**Comment by TerryLovesLife** [comment]
Sorry. My mistake. I delete the ILSVRC2015 and link to my download dataset.  Solved, thank you.

**Comment by Sanku-Yogesh** [comment]
hi, which dataset exactly we need to download could u please refer to this comment https://github.com/Scalsol/mega.pytorch/issues/73#issue-754884469
