### ISSUE TITLE
Official MXNet@(commit 62ecb60)  can not be clone any more

### ISSUE THREAD

**Issue by TerryLovesLife** [msracver/Deep-Feature-Flow#17]
Hi 

When I try to clone the  MXNet@(commit 62ecb60)  branch using below command, 

git clone --recursive -b 62ecb60 https://github.com/dmlc/mxnet

it shows   fatal: Remote branch 62ecb60 not found, how can I get the MXNet@(commit 62ecb60) ?   Have you tested on the latest mxnet 0.10.0 for Deep Feature Flow code ?

Thank you for your help.

**Comment by einsiedler0408** [comment]
Please read our updated README.md:

3.1 Clone MXNet and checkout to MXNet@(commit 62ecb60) by
```
git clone --recursive https://github.com/dmlc/mxnet.git
git checkout 62ecb60
git submodule update
```

**Comment by TerryLovesLife** [comment]
Solved. Thank you for so detailed guidance.
