### ISSUE TITLE
MXNET installation error(fatal: reference is not a tree: 89de7a)

### ISSUE THREAD

**Issue by seongkyun** [msracver/Deep-Feature-Flow#19]
while i follow mxnet installation

3.1 Clone MXNet and checkout to MXNet@(commit 62ecb60) by

git clone --recursive https://github.com/dmlc/mxnet.git
git checkout 62ecb60
git submodule update

after 

`git submodule update`

it prints out

fatal: reference is not a tree: 89de7ab20167909bc2c4f8acd397671c47cf3c0d
Unable to checkout '89de7ab20167909bc2c4f8acd397671c47cf3c0d' in submodule path 'cub'

if i ignore that fatal error, then another error occurs during make operation

`make -j8`

it prints out

/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
Makefile:242: recipe for target 'lib/libmxnet.so' failed
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
Makefile:264: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

please help me guyz

**Comment by andyhahaha** [comment]
I have this error too!
Please help us thx !

**Comment by Orpine** [comment]
that means mxnet cannot find cblas library, please install atlas/openblas correctly

**Comment by andyhahaha** [comment]
It works!
Thx!!

**Comment by andyhahaha** [comment]
I install mxnet successfully.
I can import mxnet in my virtual environment. 
However running 
python dff_rfcn/demo.py
or 
python rfcn/demo.py
Bugs arise
![2017-07-16 3 55 24](https://user-images.githubusercontent.com/14272969/28245688-35def770-6a3f-11e7-8a60-0ebb75942ebb.png)

Is there something wrong with my mxnet installation?
I am really new to mxnet. thanks for help!

**Comment by seongkyun** [comment]
@Orpine 
solved, thanks!

**Comment by wangzuxiu** [comment]
I install mxnet successfully.
I can import mxnet in my virtual environment.
However running
python dff_rfcn/demo.py
or
python rfcn/demo.py
![image](https://user-images.githubusercontent.com/33168348/32130321-08d88d0a-bbc9-11e7-8ecd-4926ebf2f78b.png)

I also have this error,please help me

**Comment by YuwenXiong** [comment]
@wangzuxiu you need to enable GPU support
