### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MultiProposal'

### ISSUE THREAD

**Issue by cory8249** [msracver/Deep-Feature-Flow#2]
Hi, thank you for releasing this code. However I cannot run it as expected.

```
Traceback (most recent call last):
  File "/home/cory/Deep-Feature-Flow/rfcn/demo.py", line 142, in <module>
    main()
  File "/home/cory/Deep-Feature-Flow/rfcn/demo.py", line 49, in main
    sym = sym_instance.get_test_symbol(config)
  File "/home/cory/Deep-Feature-Flow/rfcn/symbols/resnet_v1_101_rfcn.py", line 628, in get_test_symbol
    rois = mx.contrib.sym.MultiProposal(
AttributeError: 'module' object has no attribute 'MultiProposal'
```

I followed every step mentioned in this repo. Recompiling MXNet with operator_cxx  worked very well. But in python code it seems not found these ops.

However, I can build and run [Deformable-ConvNets](https://github.com/msracver/Deformable-ConvNets) without any error. The building processes of these 2 repos are almost the same. Can you please give me some hint ?

My PC: Ubuntu 16.04, Anaconda 2, CUDA 8, CUDNN 5.1

**Comment by Orpine** [comment]
Hi, please make sure you use the correct MXNet, you can print mxnet.\_\_path\_\_ to verify it.

**Comment by cory8249** [comment]
The mxnet.__path__ is correct. ($HOME/mxnet/python/mxnet)

I reset mxnet directory by using ($git clean -d -x -f) and rebuild it with operator_cxx . Everything works fine. Maybe there are some conflicts between anaconda and system's python. Or I typed something wrong in previous build. (for ananconda **do not use 'sudo'**, only python setup.py install will work)

Thank you for help.

**Comment by einsiedler0408** [comment]
solved

**Comment by balabala7776** [comment]
how to solve the problem
