### ISSUE TITLE
ImportError: cannot import name 'bbox_overlaps_cython'

### ISSUE THREAD

**Issue by chencjiajy** [msracver/Deep-Feature-Flow#21]
When I run  the demo, I met the problem:
Traceback (most recent call last):
  File "./rfcn/demo.py", line 18, in <module>
    from utils.image import resize, transform
  File "/home/Deep-Feature-Flow/rfcn/../lib/utils/image.py", line 6, in <module>
    from bbox.bbox_transform import clip_boxes
  File "/home/Deep-Feature-Flow/rfcn/../lib/bbox/bbox_transform.py", line 2, in <module>
    from bbox import bbox_overlaps_cython
ImportError: cannot import name 'bbox_overlaps_cython'
 
Maybe it's a problem with cython, but I don't know how to solve it.
python and cython is with anaconda3

**Comment by Orpine** [comment]
please run init.sh first

**Comment by chencjiajy** [comment]
I have run it before I run the demo

**Comment by Orpine** [comment]
Also, we do not support python3/anaconda3 by now.

**Comment by Gyiming** [comment]
Hi,
    How did you solve it? I met the same problem.

**Comment by tensor-flower** [comment]
Is that clannad

**Comment by shirishr** [comment]
No Python3 support? It's a pity !! Sorry to hear that

**Comment by yongfang1995** [comment]
I met the same problem,is it caused by python3? Should i change my python version to python2?

**Comment by vincent-26** [comment]
Hi, I followed your advice using python 2, first launching the command init.bat and then demo.py.
But the problem remains the same 

` from bbox.bbox import bbox_overlaps_cython`
> ImportError: No module named bbox

**Comment by Gmy12138** [comment]
Have you solved the problem @chencjiajy

**Comment by chencjiajy** [comment]
> Have you solved the problem @chencjiajy
@Gmy12138  Sorry, I can't remember the detail, I suppose I changed python 3 to python 2 and solved it.
