### ISSUE TITLE
Why multiply 2.5 to the output of flownet?

### ISSUE THREAD

**Issue by andyhahaha** [msracver/Deep-Feature-Flow#23]
https://github.com/msracver/Deep-Feature-Flow/blob/master/dff_rfcn/symbols/resnet_v1_101_flownet_rfcn.py#L539

I wondering why multiplying 2.5 to the output of flownet?
I didn't see any description in paper.
Thanks for your help!

**Comment by einsiedler0408** [comment]
That's because the original flownet need to multiply 20.0 to get the optical flow. They divided the groundtruth optical flow by 20.0 during training. Here we need optical flow with 1/8 input size of the flownet, so instead of multiplying 20.0, we multiply it by 20.0 / 8.0 = 2.5

**Comment by andyhahaha** [comment]
Thanks for your answer!
But I still confuse about what is the unit of the flow from optical flow groundtruth?
Is it pixel?   flow (5,5) means moving right 5 pixels and bottom 5 pixels?

Double confirm 
The reason why we need 1/8 of flownet output is because resnet101 output 1/16 input size of feature, but  flownet output 1/2 input size of flow map, so we need to scale the flow 1/8 smaller.
Am I right?

Very thanks for your help!

**Comment by einsiedler0408** [comment]
1. In DFF, the unit of the feature flow (output from flownet) is pixel in feature maps. Flow (5,5) means moving right 5 pixels and bottom 5 pixels in that feature map.
2. Resnet101 output feature maps of 1/16 input size, and the original flownet output optical flow of 1/4 input size. We first feed 1/2 input size image to flownet, and then further downsample the output optical flow to 1/2 output size. So we use optical flow of 1/8 flownet input size, which is 1/16 resnet input size.

**Comment by andyhahaha** [comment]
I got it !
Thanks for you clear explanation !
