### ISSUE TITLE
How can I run the segmentation example?

### ISSUE THREAD

**Issue by aromazyl** [msracver/Deep-Feature-Flow#24]
I cannot find any code example for video segmentation. Anyone can help me?

**Comment by chowkamlee81** [comment]
@aromazyl if you have worked on example for video segmentation on cityscape dataset, kindly share it. Pls do the needful

**Comment by aromazyl** [comment]
@chowkamlee81 I finally give up using mxnet to build net. By using tensorflow, I implement tencent's paper. Ref: https://github.com/aromazyl/tensorflow-model-yard

**Comment by aromazyl** [comment]
@chowkamlee81 I cannot even download the cityscape data.

**Comment by chowkamlee81** [comment]
You have to register ur name to that website and ake permission rights to download the dataset. for 
Your internet needs to be faster for Data downloading

**Comment by qwenqw** [comment]
@chowkamlee81 Hi，did you use it on video segmantation successfully? Can you kindly help me work on it? I'd be very grateful.
