### ISSUE TITLE
Can you provide other net drive links?

### ISSUE THREAD

**Issue by SaberArthurus** [msracver/Deep-Feature-Flow#28]
Such as Baidu Yun Driver

**Comment by HXKwindwizard** [comment]
If your are walled, you can try Psiphon 3 to get it. (Shadowsocks seems not work)

**Comment by HXKwindwizard** [comment]
If your are walled, you can try Psiphon 3 to get it. (Shadowsocks seems not working)

**Comment by YuwenXiong** [comment]
Try https://pan.baidu.com/s/1nuPULnj
