### ISSUE TITLE
demo.py cannot reproduce the result of the demo video on Youtube

### ISSUE THREAD

**Issue by GengZ** [msracver/Deep-Feature-Flow#33]
Hi, I was using the **demo.py** under _./rfcn & ./dff-rfcn_ folder. Then I checked the result in the ./demo/. The result of RFCN indicated that part worked fine. But for the part of DFF-RFCN, it could not reproduce the result of the demo video. Need I train this net myself to reproduce the result of the video?

**Comment by andyhahaha** [comment]
Hi GengZ,
I found that the image_names from here are not in order.
https://github.com/msracver/Deep-Feature-Flow/blob/master/dff_rfcn/demo.py#L64
DFF-RFCN should process frame in order to calculate reasoning flow.
I add this code to sort the image_names and it work fine. 
image_names.sort()

**Comment by GengZ** [comment]
@andyhahaha gr8 thx, it works now :+1:
