### ISSUE TITLE
Install error (Cython compilation failed)

### ISSUE THREAD

**Issue by zhanghanduo** [msracver/Deep-Feature-Flow#56]
On Ubuntu 16 with python 2.7 and cuda 9.0, I ran `init.sh` and met the following output error:

![12](https://user-images.githubusercontent.com/8006682/41450209-ae5874dc-7098-11e8-832b-f8828bc9d66f.png)
It seems when building gpu nms cython the error occurs. So is it nms dependency problem? The output hints are oblique. Thank you!

**Comment by lorenz-lukas** [comment]
did you solve the issue?

**Comment by lorenz-lukas** [comment]
Same issue here, any solution?

**Comment by samanthawyf** [comment]
Met the same problem. Have you solved it and how? @zhanghanduo

**Comment by zhanghanduo** [comment]
@samanthawyf No. Recently I was busy with something else... I will try another computer with cuda 8 and tell you.

**Comment by zhanglanqing** [comment]
I just delete all the comment lines in "gpu_nms.pyx" which starts with '//', recompile and sovle the problem.

@zhanghanduo 
@samanthawyf 
@lorenz-lukas

**Comment by zhanghanduo** [comment]
Wow! Thanks @zhanglanqing. I could compile it this way. I decide to keep this issue open to let more people see. Or you could make a pull request @zhanglanqing

**Comment by taokong** [comment]
the bug has been fixed.
