### ISSUE TITLE
problem with ’saving annotations cache to ./data/cache/ImageNetVID_VID_val_videos_annotation.pkl’

### ISSUE THREAD

**Issue by yuexin666** [msracver/Deep-Feature-Flow#63]
after 2 epochs training, when end to end train-and-test comes to this phrase, it stops at this point and doesn't continue, no error reported, the program is still running, but stucks here.

**Comment by ZhihuaGao** [comment]
That is really strange

**Comment by xuwentang** [comment]
hello  !  I run the test code , the page stays in "Writing all ImageNetVID results file", can you help me .thank you very much !

**Comment by yuexin666** [comment]
first I tried on my notebook with 8G memory,it appended this problem, and then I tried it on the server with 64G memory, it successfully operated. So, I think it's because of small memory.

**Comment by xuwentang** [comment]
thank you !
