### ISSUE TITLE
run the demo

### ISSUE THREAD

**Issue by ceiba-w** [msracver/Deep-Feature-Flow#9]
Hi, @daijifeng001 
Thanks for releasing this package.
I got into trouble when I tried to run the demo 'python ./rfcn/demo.py',and it is like that **AttributeError: 'module' object has no attribute 'MultiProposal' **.

I have copied operators in ./rfcn/operator_cxx to $(YOUR_MXNET_FOLDER)/src/operator/contrib and recompiled MXNet successfully. By the way, I copied just like this,` cp  ./rfcn/operator_cxx/*  $(YOUR_MXNET_FOLDER)/src/operator/contrib/*`, and I also tried to copy the folder, `cp  -rf ./rfcn/operator_cxx  $(YOUR_MXNET_FOLDER)/src/operator/contrib `.

So, does anything go wrong?  What should I do?
Thanks.

**Comment by Orpine** [comment]
Did you forgot to install new MXNet package?

**Comment by ceiba-w** [comment]
Yes，after compiling MXNet，  I installed the new package, `python setup.py install` .

**Comment by ceiba-w** [comment]
After compiling MXNet， I installed the new package, `python setup.py install` , but it still did not work.

**Comment by ceiba-w** [comment]
Sorry, I checked  all the four terms you mentioned in the FAQ, but it still did not work.  

And I re-examine the error, and it showed like `File "/home/xx/dff/rfcn/symbols/resnet_v1_101_rfcn.py", line 627, in get_test_symbol
    rois = mx.contrib.sym.MultiProposal(    
AttributeError: 'module' object has no attribute 'MultiProposal'`.

So  I am wondering, is there anything that needed to change in the file `$(YOUR_MXNET_FOLDER)/python/mxnet/contrib/symbol.py` ?

Thanks.

**Comment by Lucien7786** [comment]
@ceiba-w Which one did you use? MXNet(latest version) or MXNet@(commit 62ecb60)?

**Comment by ceiba-w** [comment]
@Lucien7786 Both versions were tried.

**Comment by ceiba-w** [comment]
I got it , and I forgot adding the mxnet to my path. 

Thank you all.
